### ISSUE TITLE
Allow connection to PostgreSQL database with no TLS encryption

### ISSUE THREAD

**Issue by wolfwander** [OpenBMP/obmp-psql#3]
Would it be possible to change [PSQLHandler.java](https://github.com/OpenBMP/obmp-psql/blob/main/src/main/java/org/openbmp/PSQLHandler.java) and [Config.java](https://github.com/OpenBMP/obmp-psql/blob/main/src/main/java/org/openbmp/Config.java) to allow non ecrypted connections with PostgreSQL database according to the content of file **/config/obmp-psql.yml** or env vars, keeping encrypted connections as default?

**Comment by TimEvens** [comment]
Yes, that should be a configuration knob. We will add the connection parameters to the configuration file.

**Comment by TimEvens** [comment]
The change also includes a docker change for ENV settings.  I'll update the docker repo with those details.
